### ISSUE TITLE
Wallbox data

### ISSUE THREAD

**Issue by lorbetzki** [pvtom/rscp2mqtt#12]
I love your tool and would like to know if there are any plans to query wallbox data?

**Comment by pvtom** [comment]
Hello Kristian,
yes, I am in the process of implementing the connection of a wallbox. Unfortunately I do not have a wallbox from E3/DC. Therefore I need support to test the implementation. I have seen your pull request and it corresponds to the changes I have already made. I hope to make a first update very soon. Sorry for the late reply.
Gruß Thomas

**Comment by pvtom** [comment]
git clone --branch wallbox https://github.com/pvtom/rscp2mqtt.git
