### ISSUE TITLE
AES Password ?

### ISSUE THREAD

**Issue by tognellap** [pvtom/rscp2mqtt#31]
Hi together

I am just preparing the config file and wondering what i have to do with the AES Password. Do i have to encrypt my password?

Regards

Patrick

**Comment by pvtom** [comment]
Hi Patrick,
you have to configure the RSCP password in your device (Personalisieren / Benutzerprofil).

![s10_rscp_password](https://github.com/pvtom/rscp2mqtt/assets/95747225/8988f69c-d4d5-4cc6-8a99-b9290c6625ad)

Use the same password in the .config file for the attribute E3DC_AES_PASSWORD.

Best regards
Thomas

**Comment by tognellap** [comment]
Thanks that means the Password in the config is the is the Password from the Portal?

**Comment by pvtom** [comment]
No, it's a different password you have to create in the S10 device directly.
Please fill the text field "RSCP-Passwort (min. 6 Zeichen)".
.config:
E3DC_PASSWORD= (Portal password)
E3DC_AES_PASSWORD= (RSCP password)

Best regards
Thomas

**Comment by tognellap** [comment]
Thanks that helps, regards from Switzerland,  Patrick

**Comment by timmost** [comment]
Small add on - password needs to be 6 Char length min, otherwise E3DC adds some chars... making it invalid... (see docs).
