### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by JensHauser** [pvtom/rscp2mqtt#38]
Daily, weekly, yearly historica data - how to manage this?
Can I give a specific date or a range?

**Comment by pvtom** [comment]
Hi Jens,

as mentioned in TOPICS.md. energy, autarky and SOC values are from today, yesterday, the current week, the current month and the current year.
You can configure the year of the installation of your device. rscp2mqtt will generate topics for past years e.g. "e3dc/history/2022/autarky".

Best regards
Thomas

**Comment by JensHauser** [comment]
Thanks a lot.
I just asked myself, if the historical data of last [x] days, weeks would be possible to be grabbed :-)

**Comment by zutewas** [comment]
Thanks for working on rscp2mqtt. 

It is possible to implement history data for months of the past years.

e.g. like topics
e3dc/history/2022/01/autarky
e3dc/history/2022/01/battery/energy/charge
e3dc/history/2022/01/consumed
e3dc/history/2022/01/battery/energy/discharge
e3dc/history/2022/01/grid/energy/in
e3dc/history/2022/01/grid/energy/out
e3dc/history/2022/01/home/energy
e3dc/history/2022/01/solar/energy

A other possiblity could be to request a period e.g. via e3dc/set/force and the message "20220101-20220131" for special days or "202201" for this month or "202201-202203" for three months. The return similar like the yearly history.

For me it is important to see the past months to compare it with past years.
