### ISSUE TITLE
Detailed historical consumption from e3DC

### ISSUE THREAD

**Issue by timmost** [pvtom/rscp2mqtt#40]
Hi Tom,
noch zwei Fragen zu den historischen Werten:

Die e3DC liefert ja werte für "yesterday", "week", "month", "year". Weiterhin gibt es das Topic "history" nach Jahren geordnet. 

- Gibt es auch die Tageswerte über die gesamte Laufzeit? (Oder macht die e3DC eine Aggregation und wirft die Messwerte dann weg?). Das Portal zeigt diese Werte an, wenn ich mich richtig erinnere.. vielleicht sind sie nicht in der Schnittstelle drin. 
- Gibt es einen Zeitstempel für diese Werte - "Yesterday" ist halt nur in Verbindung mit dem Lesezeitpunkt sinnvoll (geht in Grafana, ist aber nicht so schön...)

VG TImmo
(hoffe, dass das der richtige Kanal für solche Fragen ist - oder hast Du ein separates Forum?)

**Comment by pvtom** [comment]
Hallo Timmo,

die Tageswerte (auch Wochen-, Monatswerte), die man über das Portal einsehen kann, kann man grundsätzlich auch über die RSCP-Schnittstelle auslesen. Ich habe mich für die vergangenen Jahre und Yesterday entschieden, weil es von der Anzahl überschaubar bleibt. Die Yesterday-Werte z.B. schreibe ich nachts in eine Mail an mich.

Wenn man alle Tage seit Einschalten des Hauskraftwerks ausgibt, kommt bei einem Programmstart eine Menge Traffic auf. Von daher ist die Frage, was man hier sinnvoll umsetzen kann/sollte. Insbesondere, wenn andere User (wie in Issue #38) eine andere Aufteilung (monatsweise) wünschen. Evtl. ist die Idee, dass man über "e3dc/set/..."-Kommandos nach Tagen etc. anfragen kann, besser?!

Ich bastele immer mal wieder an History-Abfragen, weil mich der Gedanke zu weiteren historischen Werten auch seit Längerem umtreibt. 
Bei der Abfrage muss man die Start- und die Endsekunde des Tages, des Monats, des Jahres (UNIX Epoche, seit 1.1.1970) mitgeben, dabei die Schalttage und Monatslängen berücksichtigen. Teilweise hatte ich beim Basteln allerdings Probleme, trotz der korrekten Zeitspannen, die gleichen Werte wie im Portal zu ermitteln. Insb. konnte ich Schalttage nicht korrekt abfragen. Hier hat E3DC scheinbar mittlerweile etwas geändert. Im Portal wurde bis von ein paar Monaten für einen Schalttag zwei Zeitbereiche (vor und nach der Zeitumstellung) ausgegeben. Das konnte ich über RSCP nicht nachvollziehen... es gibt dabei also auch Herausforderungen, die mich bisher davon abgehalten haben, eine weitergehende Lösung für rscp2mqtt zu bauen.

Zur Frage nach dem Zeitstempel: Ist mir nicht bekannt, würde ich mir auch zur besseren Zuordnung der zurückgelieferten Werte wünschen.

Gruß
Thomas

**Comment by timmost** [comment]
Hi Thomas

kann ich nachvollziehen, habe gerade auch nochmals geschaut und das hier gefunden:

**Comment by pvtom** [comment]
Neu mit Release v3.11:
Historical data for a specific day (format "YYYY-MM-DD") can be queried by
mosquitto_pub -h localhost -p 1883 -t "e3dc/set/request/day" -m "2024-01-01"

Please use the script request_days.sh to request data for a time span.
./request_days.sh localhost 1883 e3dc 2024-01-01 2024-01-13

**Comment by timmost** [comment]
Cool!

**Comment by docolli** [comment]
Bei mir werden seit dieser Version jeden Tag die historischen Tagesdaten als neues MQTT Topic gepublished. Kann ich die automatische Ausgabe der "day" Werte irgendwie in der config verhindern? Ich brauche die nicht.

Beispielwerte:
```
...
rscp2mqtt:e3dc/day/2024/2/9/autarky:.* 2_9_autarky
rscp2mqtt:e3dc/day/2024/2/10/battery/energy/charge:.* charge
rscp2mqtt:e3dc/day/2024/2/10/battery/energy/discharge:.* discharge
rscp2mqtt:e3dc/day/2024/2/10/solar/energy:.* energy
rscp2mqtt:e3dc/day/2024/2/10/grid/energy/in:.* in
rscp2mqtt:e3dc/day/2024/2/10/grid/energy/out:.* out
rscp2mqtt:e3dc/day/2024/2/10/home/energy:.* energy
rscp2mqtt:e3dc/day/2024/2/10/battery/rsoc:.* rsoc
rscp2mqtt:e3dc/day/2024/2/10/consumed:.* 2_10_consumed
rscp2mqtt:e3dc/day/2024/2/10/autarky:.* 2_10_autarky
rscp2mqtt:e3dc/day/2024/2/11/battery/energy/charge:.* charge
rscp2mqtt:e3dc/day/2024/2/11/battery/energy/discharge:.* discharge
rscp2mqtt:e3dc/day/2024/2/11/solar/energy:.* energy
rscp2mqtt:e3dc/day/2024/2/11/grid/energy/in:.* in
rscp2mqtt:e3dc/day/2024/2/11/grid/energy/out:.* out
rscp2mqtt:e3dc/day/2024/2/11/home/energy:.* energy
rscp2mqtt:e3dc/day/2024/2/11/battery/rsoc:.* rsoc
rscp2mqtt:e3dc/day/2024/2/11/consumed:.* 2_11_consumed
rscp2mqtt:e3dc/day/2024/2/11/autarky:.* 2_11_autarky
```

**Comment by pvtom** [comment]
@docolli
Die "day"-Werte kann man ab Release v3.15 in der .config mit
DAILY_VALUES=false
unterdrücken.

**Comment by docolli** [comment]
Schon gesehen... 😉
Vielen Dank dafür!
