### ISSUE TITLE
Add a Parameter for ID of external Powermeter

### ISSUE THREAD

**Issue by maaque** [pvtom/rscp2mqtt#45]
Great software and exactly, what I needed. Many thanks.

The ID of the external PM of my E3DC S10 is 4 and not 6. Therefore I had to change RscpMqttMain.cpp the line 
`protocol.appendValue(&PMContainer, TAG_PM_INDEX, (uint8_t)6);` to
`protocol.appendValue(&PMContainer, TAG_PM_INDEX, (uint8_t)4);`

It would be probably a good idea, to add a parameter e.g. PM_INDEX to the config file.

**Comment by pvtom** [comment]
Hi maaque,
thank you for your feedback. 
It is exciting to see the differences between the S10 systems.
I will implement this as a configuration option in the next version.

Best regards
Thomas

**Comment by maaque** [comment]
Perfekt

Viele Grüße 
Matthias

**Comment by pvtom** [comment]
Fixed by release v3.14.

Please add the line to your .config:
PM_INDEX=4
and remove:
PM_EXTERN=true

**Comment by maaque** [comment]
Works perfectly. Thanks
