### ISSUE TITLE
Historical Day Data for the Start Year not working

### ISSUE THREAD

**Issue by RobertHerter** [pvtom/rscp2mqtt#48]
Hello,

For the configured Startyear the History-Data is not requested.

x.year > cfg.history_start_year schould be  x.year >= cfg.history_start_year

**Comment by pvtom** [comment]
Hi Robert,
thank you. I will fix it with the next release v3.15.
Best regards
Thomas

**Comment by pvtom** [comment]
fixed by v3.15
