### ISSUE TITLE
Testing more Wallbox Tags

### ISSUE THREAD

**Issue by docolli** [pvtom/rscp2mqtt#54]
Wow, reading rscplib.js I am overwhelmed with possible Tags😮...

Let's use the dev branch to test some Tags and see what the returned values are and how usefull they might be for users.

### Some general information Tags
```
WB_STATUS	E800004
WB_ERROR_CODE	E800005
WB_MODE	E800006
WB_APP_SOFTWARE	E800007
WB_BOOTLOADER_SOFTWARE	E800008
WB_HW_VERSION	E800009
WB_FLASH_VERSION	E80000A
WB_DEVICE_ID	E80000B
WB_PM_MODE	E800011
WB_PM_DEVICE_ID	E800015
WB_PM_ERROR_CODE	E800016
WB_PM_FIRMWARE_VERSION	E800017
WB_PM_DEVICE_STATE	E800029
WB_FIRMWARE_VERSION	E80002F
WB_DEVICE_NAME	E800042
```

### Some power related Tags
```
WB_AVAILABLE_SOLAR_POWER	E841000
WB_SUN_MODE_ACTIVE	E841038
```

### Some network related Tags
```
WB_MAC_ADDRESS	E841022
WB_GATEWAY	E841031
WB_SUBNET_MASK	E841032
WB_IP_ADDR	E841033
WB_DHCP_ENABLED	E841034
WB_WALLBOX_TYPE	E841036
```

Would be cool, if you could implement them for testing. 
Or let me know, how I need to modify the code to implement them in my local copy for testing the Tags.

**Comment by pvtom** [comment]
Please use
- Additional tags and topics by configuration
- Raw data mode
for testing new tags. Functionality is available since release v3.26.
So I close this issue.
