### ISSUE TITLE
ENERGY per String

### ISSUE THREAD

**Issue by MyGitIT** [pvtom/rscp2mqtt#57]
Hi,

short question, is it possible to select the e3dc/pvi/energy/string_x (today) instead off e3dc/pvi/energy_all/string_x (all time)?

This would be great!

Thx

**Comment by pvtom** [comment]
Hi,
the S10 device only provides the total energy values via the interface. Daily values can be calculated by memorizing the values at the change of day. I like the idea and will implement it soon.
Best regards
Thomas

**Comment by pvtom** [comment]
implemented with release v3.19.
New topic: e3dc/pvi/energy/string_x for the daily values.

**Comment by MyGitIT** [comment]
Hi Thomas,

vielen Dank, wird das Topic auch in INFLUX geschrieben?

**Comment by pvtom** [comment]
Hi Sven,
Deine Frage hat mich stutzig gemacht.
Das Topic soll natürlich auch in die InfluxDB geschrieben werden.
Nur leider passiert das nicht. Grrrh. Ein Problem mit der Reihenfolge: Einrichten des Topics, Setzen des InfluxDB-Flags... es sind auch noch andere Topics, die dynamisch angelegt werden, betroffen.
Das wird mit dem nächsten Release dann gefixt. Also Danke für Deine Nachfrage :-)
Gruß Thomas

**Comment by pvtom** [comment]
Reopen, da Topic nicht in die InfluxDB geschrieben wird.

**Comment by pvtom** [comment]
Die Lösung steht jetzt mit v3.20 zur Verfügung.

**Comment by MyGitIT** [comment]
Hi Thomas,

die Topics sind in der Datenbank, danke dafür. Aber kann es sein, dass die Werte nur auf Stundenbasis und nicht auf Tag aggregiert werden?

Gruß Sven

**Comment by pvtom** [comment]
Hallo Sven,
die Werte werden für den aktuellen Tag aggregiert. Dazu wird der Wert um Mitternacht als Startwert gespeichert und dann zur Berechnung des Tageswerts benutzt (aktueller Wert minus Startwert).
Das klappt natürlich nach Neustart des Programms erst richtig für den nächsten Tag. Evtl. kommen Dir die Werte gerade daher nicht richtig vor.
Mit RETAIN_FOR_SETUP=true in der .config wird der Startwert im MQTT als retained Topic gespeichert und nach dem Neustart eingelesen. So überlebt der Startwert einen Neustart von rscp2mqtt. Mit v3.20 hat sich allerdings das Format ein wenig geändert ggü. v3.19, von daher zieht ein vorhandener Startwert bei Wechsel auf v3.20 erstmal nicht. Auch das regelt die nächste Mitternacht.
Ich hoffe, das passt so?
Gruß Thomas

**Comment by MyGitIT** [comment]
Hallo Thomas,

der neue Stringwert passt:

InfluxDB:
![Bildschirmfoto vom 2024-04-21 20-30-59](https://github.com/pvtom/rscp2mqtt/assets/79418392/6598a80a-c8f5-46aa-baa4-c1c53a619d21)

E3DC-Portal:
![Bildschirmfoto vom 2024-04-21 20-35-19](https://github.com/pvtom/rscp2mqtt/assets/79418392/2ec7c4ad-ad76-481f-a592-4507802a7b9f)

Perfekt, vielen, vielen Dank!

Gruß Sven
