### ISSUE TITLE
systemd service

### ISSUE THREAD

**Issue by LaborEtArs** [pvtom/rscp2mqtt#6]
Happy New Year, too!
No really an issue, but an extension (I'm a bit left handed using git pull requests...).
Started using RSCP2MQTT only a few hours ago and found it really great; this is exactly what I was looking for :-)
Hence I created a systemd service to auto-start it on my RPi:

###

[Unit]
Description=RSCP2MQTT service
After=network.target
After=systemd-user-sessions.service
After=network-online.target

[Service]
User=pi
Type=forking
WorkingDirectory=/opt/rscp2mqtt
ExecStart=/opt/rscp2mqtt/rscp2mqtt -d
ExecStop=pkill rscp2mqtt
TimeoutSec=30
Restart=on-failure
RestartSec=30
StartLimitInterval=350
StartLimitBurst=10
 
[Install]
WantedBy=multi-user.target

###

Maybe helpful to others :-)

Create as 'rscp2mqtt.service' in '/etc/systemd/system/'
Config with 'sudo nano rscp2mqtt.service' (adjust USER 'User'=pi, if needed)
Start: sudo systemctl start rscp2mqtt
Install: sudo systemctl enable rscp2mqtt

**Comment by pvtom** [comment]
closed with v2.7
