### ISSUE TITLE
TOPICS die bei jedem Durchlauf geschrieben werden sollen

### ISSUE THREAD

**Issue by MyGitIT** [pvtom/rscp2mqtt#60]
Hallo Thomas,

da ich die rscp2mqtt Daten in eine Influxdb schreibe, bräuchte ich die Möglichkeit folgende TOPICS bei jedem Durchlauf zu schreiben, momentan funktioniert das nicht bei allen z.b. e3dc/wallbox/power/total. Dadurch entstehen Lücken und unschöne Graphen Verläufe (siehe Bild)

![Bildschirmfoto vom 2024-04-09 15-28-02](https://github.com/pvtom/rscp2mqtt/assets/79418392/55adb05e-c087-4e5c-905c-ebbea7215dc0)

FORCE_TOPIC=e3dc/[a-z]+/power
FORCE_TOPIC=e3dc/[a-z]+/energy
FORCE_TOPIC=e3dc/grid/energy/[a-z]+
FORCE_TOPIC=e3dc/wallbox/[a-z]+/total
FORCE_TOPIC=e3dc/wallbox/[a-z]+/solar
FORCE_TOPIC=e3dc/pvi/[a-z]+/string_[1-2]
FORCE_TOPIC=e3dc/battery/energy/[a-z]+
FORCE_TOPIC=e3dc/battery/soc
FORCE_TOPIC=e3dc/battery/soh
FORCE_TOPIC=e3dc/battery/dcb/[1-4]/soh
FORCE_TOPIC=e3dc/battery/dcb/[1-4]/soc
FORCE_TOPIC=e3dc/battery/temperature/.*

Die TOPICS für Grafana sehen genauso aus.

Mache ich da etwas verkehrt?

Gruß Sven

**Comment by pvtom** [comment]
Hallo Sven,

das steuernde Attribut im .config heißt FORCE_PUB und nicht TOPIC_PUB. ;-)

Gruß Thomas
