### ISSUE TITLE
Absturz nach mehreren Stunden

### ISSUE THREAD

**Issue by lorbetzki** [pvtom/rscp2mqtt#67]
Hi,

ich bekomme nach einigen Stunden folgenden Fehler
![image](https://github.com/pvtom/rscp2mqtt/assets/57233317/da170171-b182-47a7-ae7b-4b0cb89cae54)

`RscpMqttMain.cpp(2205) Error: Socketreceive Error errno 4
`es wird zwar eine neue Verbindung aufgebaut, aber keine Daten empfangen. Danach breche ich mit Strg+c ab und bekomme 
`double free or corruption (out)`

Der Fehler tritt seit Version 3.19 auf, davor habe ich den Fehler nicht. Eine Idee?

**Comment by pvtom** [comment]
Hi Kristian,
immer wieder spannend, was so auftaucht.
errno 4 ist der Output der recv-Funktion (Lesen vom Netzwerk-Socket) und steht für EINTR.
Der Status wird derzeit nicht korrekt behandelt.
Ich hoffe, Google hat hier recht und den richtigen Vorschlag gemacht.
Wenn Du möchtest, könntest Du Zeile 2204 in der Datei RscpMqttMain.cpp so abändern:

if ((errno == EAGAIN) || (errno == EWOULDBLOCK) || (errno == EINTR)) continue;

Ich hoffe, das hilft?!

Gruß Thomas

**Comment by lorbetzki** [comment]
Alles klar, ich habe die Änderung vorgenommen, kompiliert und gestartet. Ich melde mich. Danke schonmal

**Comment by lorbetzki** [comment]
alles ich würde sagen, der Fehler ist mit obiger Änderung behoben. Seither keine Abstürze mehr. Vielen Dank für die prompte Unterstützung

**Comment by pvtom** [comment]
Das freut mich, prima. Danke fürs Testen!

**Comment by pvtom** [comment]
Die Lösung ist jetzt in das neue Release v3.23 eingeflossen.
