### ISSUE TITLE
1/0 instead of true/false

### ISSUE THREAD

**Issue by maaque** [pvtom/rscp2mqtt#68]
Again, many thanks for the great and reliable piece of software.
Maybe I missed this topic in the docs, but It would be nice to have as return 0 or 1 instead of true and false. By doing so, it could directly feed any automation, without translating the words to 0 or 1. 
May, if case there is an elegant way to do it, it should be configurable for all, or may just for few parameter

Regards
Maaque

**Comment by pvtom** [comment]
Hi Maaque,
good idea, thank you.
I have implemented this feature with v3.23.
Please put this line into your .config:
USE_TRUE_FALSE=false
Best regards
Thomas

**Comment by maaque** [comment]
Works perfectly well.

Thanks
Maaqie

**Comment by pvtom** [comment]
:-)
