### ISSUE TITLE
Min. Charge/Discharge Limit

### ISSUE THREAD

**Issue by genezig** [pvtom/rscp2mqtt#74]
Hi there,

I noticed that in RSCPgui it is possible to change the min. charge/discharge limit. It seems to control the minimum power for the battery to be discharged or charged with. Since 2.2 kW is the minimum recommended charge power for the S10E (I remember the value, but not where I read it) I would be glad to be able to control that value. Would be valuable on sunny days with occasional clouds passing by resulting in fluctuations of the solar power.

rscp2mqtt provides the mqtt topic ems/discharge_start/power, but it does not provide the corresponding set/discharge_start_power topic to change this value.

Would be great if it could be implemented.

Best regards

**Comment by pvtom** [comment]
Hi,
it should be possible with "Power Limits"...
![grafik](https://github.com/pvtom/rscp2mqtt/assets/95747225/673ab459-e477-4a38-ac4e-fb52007017df)

Best regards
Thomas

**Comment by genezig** [comment]
Thank you for the quick reply. The power limit values mentioned in your screenshot set the _maximum_ charge/discharge power. The value reported by ems/discharge_start/power is a _minimum_ value. Charging as well as discharging only takes place if the charging/discharging power is _above_ this value. I believe the standard value is 65 W and it is meant to save the battery or other electronic units from switching from charge to discharge and vice versa too often. I would be glad to be able to set that value as mentioned in my opening post.

Best regards

**Comment by pvtom** [comment]
Okay, sorry, I didn't read that correctly. I have already adapted the tool and it works.
I will bring the solution with the next release - probably next weekend.
Best regards
Thomas

**Comment by genezig** [comment]
At the speed of light - thank you, I really appreciate it!

Best regards

**Comment by pvtom** [comment]
Release v3.25 is available.
