### ISSUE TITLE
e3dc/set/max_discharge_power not working for me

### ISSUE THREAD

**Issue by JensHauser** [pvtom/rscp2mqtt#86]
Hi,

I do have a S10X 14 compact with additional 10KWh battery, SW version H20_2024_024.
What I want to achieve is, denying discharging of the battery in order to offer the PV power to the wallbox.

* Setting power limits on/off works
 mosquitto_pub -h 192.168.2.xx -p 1883 -t "e3dc/set/power_limits" -m true

* Setting discharging limit to 0 does not work
mosquitto_pub -h 192.168.2.xx -p 1883 -t "e3dc/set/max_discharge_power" -m 0
I see no change in the mqtt explorer

Looks like this at the moment
![grafik](https://github.com/user-attachments/assets/277d78ae-da88-4b75-ae8c-25ec43fd2087)

BR Jens

**Comment by pvtom** [comment]
Hello Jens,
"power_limits" are only intended to reduce the charging or discharging power (not to 0).
To stop charging/discharging completely, there are so-called idle periods. 
These can be set e.g. via mosquitto_pub -h localhost -p 1883 -t "e3dc/set/idle_period" -m "today:discharge:true:00:00:00-23:59" for a specific time range.
However, it is probably easier to use the SOC limiter of rscp2mqtt: 
mosquitto_pub -h localhost -p 1883 -t "e3dc/set/limit/discharge/soc" -m 80 (which limits discharging down to 80% SOC)
or
mosquitto_pub -h localhost -p 1883 -t "e3dc/set/limit/discharge/by_home_power" -m 7000 (which stops discharging if more than 7000 Watt of home power is used. If you have no E3/DC wallbox, home power includes the wallbox power)

I use the tool evcc to control the wallbox. Here you can define the behaviour regarding the home battery.
Best regards
Thomas

**Comment by JensHauser** [comment]
Got it, thanks for your quick and comprehensive reply
